#!/usr/bin/env node
// Generates src/fonts.js (base64 @font-face rules) from assets/fonts/fonts.json.
//
// The generated file is gitignored: committing ~190KB of base64 on one line makes
// every diff unreadable and grows the repo on each font change. The .woff2 files
// and this script are the source of truth.
//
//   node scripts/build-fonts.mjs

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const manifest = JSON.parse(readFileSync(join(root, 'assets/fonts/fonts.json'), 'utf8'));

const faces = manifest.map(({ family, weight, style = 'normal', file }) => {
  const b64 = readFileSync(join(root, 'assets/fonts', file)).toString('base64');
  return `@font-face{font-family:'${family}';font-style:${style};font-weight:${weight};`
       + `font-display:block;src:url(data:font/woff2;base64,${b64}) format('woff2')}`;
});

const header = `// GENERATED by scripts/build-fonts.mjs - do not edit.
// Source: assets/fonts/fonts.json + the .woff2 files beside it.
// Faces are embedded as data URIs because a rasterised SVG cannot fetch
// anything: a linked font silently falls back at export time.
// All faces are SIL OFL 1.1 - see assets/fonts/licenses/ and FONTS.md.
`;

writeFileSync(join(root, 'src/fonts.js'),
  `${header}export const FONT_CSS = \`${faces.join('\n')}\`;\n`);

const kb = (n) => `${(n / 1024).toFixed(0)} KB`;
console.log(`src/fonts.js written — ${manifest.length} faces, ${kb(faces.join('').length)}`);
for (const m of manifest) console.log(`  ${m.family} ${m.weight} (${m.subset})`);
