#!/usr/bin/env node
// Emits src/fontmanifest.js from assets/fonts/fonts.json.
//
// It deliberately does NOT emit base64. Embedding fonts as data URIs cost a
// 34% size penalty on every page load, gzipped badly, and inlined ~187KB into
// every rendered SVG. Faces are served as .woff2 files and only base64'd at
// export time, when the data URIs are genuinely required.
//
//   node scripts/build-fonts.mjs

import { readFileSync, writeFileSync, statSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const faces = JSON.parse(readFileSync(join(root, 'assets/fonts/fonts.json'), 'utf8'));

writeFileSync(join(root, 'src/fontmanifest.js'),
`// GENERATED by scripts/build-fonts.mjs - do not edit.
// Source: assets/fonts/fonts.json
export const FONT_DIR = './assets/fonts/';
export const FACES = ${JSON.stringify(faces, null, 2)};
`);

const kb = (n) => (n / 1024).toFixed(1) + ' KB';
const by = {};
for (const f of faces) {
  by[f.group] = (by[f.group] || 0) + statSync(join(root, 'assets/fonts', f.file)).size;
}
console.log(`src/fontmanifest.js written — ${faces.length} faces, no base64`);
for (const [g, n] of Object.entries(by)) console.log(`  ${g.padEnd(7)} ${kb(n)}`);
